package SQLs;

import java.util.LinkedList;
import java.util.List;

public class CreateTable {	
	//List<String> tables;
	CreateTable() {
		//tables = new LinkedList<String>();
	}
	
	public static String[] getStatement() {
		String YelpBusiness =  "Create Table YelpBusiness ("
				+ "business_id VARCHAR(22),"
				+ "city VARCHAR(7),"
				+ "full_address VARCHAR(49),"
				+ "hours_Friday_close VARCHAR(5),"
				+ "hours_Friday_open VARCHAR(5),"
				+ "hours_Monday_close VARCHAR(5),"
				+ "hours_Monday_open VARCHAR(5),"
				+ "hours_Saturday_close VARCHAR(5),"
				+ "hours_Saturday_open VARCHAR(5),"
				+ "hours_Sunday_close VARCHAR(5),"
				+ "hours_Sunday_open VARCHAR(5),"
				+ "hours_Thursday_close VARCHAR(5),"
				+ "hours_Thursday_open VARCHAR(5),"
				+ "hours_Tuesday_close VARCHAR(5),"
				+ "hours_Tuesday_open VARCHAR(5),"
				+ "hours_Wednesday_close VARCHAR(5),"
				+ "hours_Wednesday_open VARCHAR(5),"
				+ "latitude BINARY_DOUBLE,"
				+ "longitude BINARY_DOUBLE,"
				+ "name VARCHAR(17),"
				+ "open CHAR(1),"
				+ "review_count Integer,"
				+ "stars BINARY_DOUBLE,"
				+ "state VARCHAR(2),"
				+ "type VARCHAR(8),"
				+ "primary key (business_id)"
				+ ")";
		
		String YelpBusinessAttributes = "create table YelpBusinessAttributes("
				+"business_id VARCHAR(22),"
				+"Credit_Cards CHAR(1),"
				+"Insurance CHAR(1),"
				+"Ages_Allowed VARCHAR(6),"
				+"Alcohol VARCHAR(4),"
				+"casual CHAR(1),"
				+"classy CHAR(1),"
				+"divey CHAR(1),"
				+"hipster CHAR(1),"
				+"intimate CHAR(1),"
				+"romantic CHAR(1),"
				+"touristy CHAR(1),"
				+"trendy CHAR(1),"
				+"upscale CHAR(1),"
				+"Attire VARCHAR(6),"
				+"BYOB CHAR(1),"
				+"BYOB_Corkage VARCHAR(2),"
				+"By_Appointment_Only CHAR(1),"
				+"Caters CHAR(1),"
				+"Coat_Check CHAR(1),"
				+"Corkage CHAR(1),"
				+"Delivery CHAR(1),"
				+"dairy_free CHAR(1),"
				+"gluten_free CHAR(1),"
				+"halal CHAR(1),"
				+"kosher CHAR(1),"
				+"soy_free CHAR(1),"
				+"vegan CHAR(1),"
				+"vegetarian CHAR(1),"
				+"Dogs_Allowed CHAR(1),"
				+"Drive_Thru CHAR(1),"
				+"Dancing CHAR(1),"
				+"Groups CHAR(1),"
				+"Kids CHAR(1),"
				+"breakfast CHAR(1),"
				+"brunch CHAR(1),"
				+"dessert CHAR(1),"
				+"dinner CHAR(1),"
				+"latenight CHAR(1),"
				+"lunch CHAR(1),"
				+"In_africanamerican CHAR(1),"
				+"In_asian CHAR(1),"
				+"In_coloring CHAR(1),"
				+"In_curly CHAR(1),"
				+"In_extensions CHAR(1),"
				+"In_kids CHAR(1),"
				+"In_perms CHAR(1),"
				+"In_straightperms CHAR(1),"
				+"Happy_Hour CHAR(1),"
				+"Has_TV CHAR(1),"
				+"background_music CHAR(1),"
				+"dj CHAR(1),"
				+"jukebox CHAR(1),"
				+"karaoke CHAR(1),"
				+"live CHAR(1),"
				+"playlist CHAR(1),"
				+"video CHAR(1),"
				+"Noise_Level VARCHAR(7),"
				+"Open_24_Hours CHAR(1),"
				+"Order_at_Counter CHAR(1),"
				+"Outdoor_Seating CHAR(1),"
				+"garage CHAR(1),"
				+"lot CHAR(1),"
				+"street CHAR(1),"
				+"valet CHAR(1),"
				+"validated CHAR(1),"
				+"amex CHAR(1),"
				+"cash_only CHAR(1),"
				+"discover CHAR(1),"
				+"mastercard CHAR(1),"
				+"visa CHAR(1),"
				+"Price_Range Integer,"
				+"Smoking VARCHAR(7),"
				+"Take_out CHAR(1),"
				+"Takes_Reservations CHAR(1),"
				+"Waiter_Service CHAR(1),"
				+"Wheelchair_Accessible CHAR(1),"
				+"Wi_Fi VARCHAR(4),"
				+"primary key (business_id),"
				+"foreign key (business_id) references YelpBusiness(business_id) on delete set null"
				+ ")";
		String YelpBusinessCategory = "create table YelpBusinessCategory ("
				+"business_id VARCHAR(22),"
				+"category VARCHAR(50),"
				+"primary key (business_id, category),"
				+"foreign key (business_id) references YelpBusiness(business_id) on delete set null"
				+ ")";
		String YelpBusinessNeighbors = "create table YelpBusinessNeighbors ("
				+"business_id VARCHAR(22),"
				+"name VARCHAR(17),"
				+"primary key (business_id, name),"
				+"foreign key (business_id) references YelpBusiness(business_id) on delete set null"
				+ ")";
		String Yelp_Review = "create table Yelp_Review("
				+"business_id VARCHAR(22),"
				+"review_date date,"
				+"review_id VARCHAR(22),"
				+"stars Integer,"
				+"text VARCHAR(534),"
				+"type VARCHAR(6),"
				+"user_id VARCHAR(22),"
				+"votes_cool Integer,"
				+"votes_funny Integer,"
				+"votes_useful Integer,"
				+"primary key (business_id)"
				+ ")";
		String Yelp_User = "create table Yelp_User ("
				+"average_stars BINARY_DOUBLE,"
				+"compliments_cool Integer,"
				+"compliments_cute Integer,"
				+"compliments_funny Integer,"
				+"compliments_hot Integer,"
				+"compliments_list Integer,"
				+"compliments_more Integer,"
				+"compliments_note Integer,"
				+"compliments_photos Integer,"
				+"compliments_plain Integer,"
				+"compliments_profile Integer,"
				+"compliments_writer Integer,"
				+"fans Integer,"
				+"name VARCHAR(3),"
				+"review_count Integer,"
				+"type VARCHAR(4),"
				+"user_id VARCHAR(22),"
				+"votes_cool Integer,"
				+"votes_funny Integer,"
				+"votes_useful Integer,"
				+"yelping_since VARCHAR(7),"
				+"primary key (user_id)"
				+ ")";
		String Yelp_User_Friend = "create table Yelp_User_Friend ("
				+"user_id VARCHAR(22),"
				+"friend_id VARCHAR(22),"
				+"primary key (user_id, friend_id),"
				+"foreign key (user_id) references Yelp_User(user_id) on delete set null"
				+ ")";
		String Yelp_Checkin = "create table Yelp_chechin ("
				+"business_id VARCHAR(22),"
				+"checkin_0_0 Integer,"
				+"checkin_0_1 Integer,"
				+"checkin_0_2 Integer,"
				+"checkin_0_3 Integer,"
				+"checkin_0_4 Integer,"
				+"checkin_0_5 Integer,"
				+"checkin_0_6 Integer,"
				+"checkin_1_0 Integer,"
				+"checkin_1_1 Integer,"
				+"checkin_1_2 Integer,"
				+"checkin_1_3 Integer,"
				+"checkin_1_4 Integer,"
				+"checkin_1_5 Integer,"
				+"checkin_1_6 Integer,"
				+"checkin_10_0 Integer,"
				+"checkin_10_1 Integer,"
				+"checkin_10_2 Integer,"
				+"checkin_10_3 Integer,"
				+"checkin_10_4 Integer,"
				+"checkin_10_5 Integer,"
				+"checkin_10_6 Integer,"
				+"checkin_11_0 Integer,"
				+"checkin_11_1 Integer,"
				+"checkin_11_2 Integer,"
				+"checkin_11_3 Integer,"
				+"checkin_11_4 Integer,"
				+"checkin_11_5 Integer,"
				+"checkin_11_6 Integer,"
				+"checkin_12_0 Integer,"
				+"checkin_12_1 Integer,"
				+"checkin_12_2 Integer,"
				+"checkin_12_3 Integer,"
				+"checkin_12_4 Integer,"
				+"checkin_12_5 Integer,"
				+"checkin_12_6 Integer,"
				+"checkin_13_0 Integer,"
				+"checkin_13_1 Integer,"
				+"checkin_13_2 Integer,"
				+"checkin_13_3 Integer,"
				+"checkin_13_4 Integer,"
				+"checkin_13_5 Integer,"
				+"checkin_13_6 Integer,"
				+"checkin_14_0 Integer,"
				+"checkin_14_1 Integer,"
				+"checkin_14_2 Integer,"
				+"checkin_14_3 Integer,"
				+"checkin_14_4 Integer,"
				+"checkin_14_5 Integer,"
				+"checkin_14_6 Integer,"
				+"checkin_15_0 Integer,"
				+"checkin_15_1 Integer,"
				+"checkin_15_2 Integer,"
				+"checkin_15_3 Integer,"
				+"checkin_15_4 Integer,"
				+"checkin_15_5 Integer,"
				+"checkin_15_6 Integer,"
				+"checkin_16_0 Integer,"
				+"checkin_16_1 Integer,"
				+"checkin_16_2 Integer,"
				+"checkin_16_3 Integer,"
				+"checkin_16_4 Integer,"
				+"checkin_16_5 Integer,"
				+"checkin_16_6 Integer,"
				+"checkin_17_0 Integer,"
				+"checkin_17_1 Integer,"
				+"checkin_17_2 Integer,"
				+"checkin_17_3 Integer,"
				+"checkin_17_4 Integer,"
				+"checkin_17_5 Integer,"
				+"checkin_17_6 Integer,"
				+"checkin_18_0 Integer,"
				+"checkin_18_1 Integer,"
				+"checkin_18_2 Integer,"
				+"checkin_18_3 Integer,"
				+"checkin_18_4 Integer,"
				+"checkin_18_5 Integer,"
				+"checkin_18_6 Integer,"
				+"checkin_19_0 Integer,"
				+"checkin_19_1 Integer,"
				+"checkin_19_2 Integer,"
				+"checkin_19_3 Integer,"
				+"checkin_19_4 Integer,"
				+"checkin_19_5 Integer,"
				+"checkin_19_6 Integer,"
				+"checkin_2_0 Integer,"
				+"checkin_2_1 Integer,"
				+"checkin_2_2 Integer,"
				+"checkin_2_3 Integer,"
				+"checkin_2_4 Integer,"
				+"checkin_2_5 Integer,"
				+"checkin_2_6 Integer,"
				+"checkin_20_0 Integer,"
				+"checkin_20_1 Integer,"
				+"checkin_20_2 Integer,"
				+"checkin_20_3 Integer,"
				+"checkin_20_4 Integer,"
				+"checkin_20_5 Integer,"
				+"checkin_20_6 Integer,"
				+"checkin_21_0 Integer,"
				+"checkin_21_1 Integer,"
				+"checkin_21_2 Integer,"
				+"checkin_21_3 Integer,"
				+"checkin_21_4 Integer,"
				+"checkin_21_5 Integer,"
				+"checkin_21_6 Integer,"
				+"checkin_22_0 Integer,"
				+"checkin_22_1 Integer,"
				+"checkin_22_2 Integer,"
				+"checkin_22_3 Integer,"
				+"checkin_22_4 Integer,"
				+"checkin_22_5 Integer,"
				+"checkin_22_6 Integer,"
				+"checkin_23_0 Integer,"
				+"checkin_23_1 Integer,"
				+"checkin_23_2 Integer,"
				+"checkin_23_3 Integer,"
				+"checkin_23_4 Integer,"
				+"checkin_23_5 Integer,"
				+"checkin_23_6 Integer,"
				+"checkin_3_0 Integer,"
				+"checkin_3_1 Integer,"
				+"checkin_3_2 Integer,"
				+"checkin_3_3 Integer,"
				+"checkin_3_4 Integer,"
				+"checkin_3_5 Integer,"
				+"checkin_3_6 Integer,"
				+"checkin_4_0 Integer,"
				+"checkin_4_1 Integer,"
				+"checkin_4_2 Integer,"
				+"checkin_4_3 Integer,"
				+"checkin_4_4 Integer,"
				+"checkin_4_5 Integer,"
				+"checkin_4_6 Integer,"
				+"checkin_5_0 Integer,"
				+"checkin_5_1 Integer,"
				+"checkin_5_2 Integer,"
				+"checkin_5_3 Integer,"
				+"checkin_5_4 Integer,"
				+"checkin_5_5 Integer,"
				+"checkin_5_6 Integer,"
				+"checkin_6_0 Integer,"
				+"checkin_6_1 Integer,"
				+"checkin_6_2 Integer,"
				+"checkin_6_3 Integer,"
				+"checkin_6_4 Integer,"
				+"checkin_6_5 Integer,"
				+"checkin_6_6 Integer,"
				+"checkin_7_0 Integer,"
				+"checkin_7_1 Integer,"
				+"checkin_7_2 Integer,"
				+"checkin_7_3 Integer,"
				+"checkin_7_4 Integer,"
				+"checkin_7_5 Integer,"
				+"checkin_7_6 Integer,"
				+"checkin_8_0 Integer,"
				+"checkin_8_1 Integer,"
				+"checkin_8_2 Integer,"
				+"checkin_8_3 Integer,"
				+"checkin_8_4 Integer,"
				+"checkin_8_5 Integer,"
				+"checkin_8_6 Integer,"
				+"checkin_9_0 Integer,"
				+"checkin_9_1 Integer,"
				+"checkin_9_2 Integer,"
				+"checkin_9_3 Integer,"
				+"checkin_9_4 Integer,"
				+"checkin_9_5 Integer,"
				+"checkin_9_6 Integer,"
				+"type VARCHAR(7),"
				+"primary key (business_id),"
				+ "foreign key (business_id) references YelpBusiness(business_id) on delete set null"
				+ ")";
		return new String[]{ YelpBusiness, YelpBusinessAttributes, YelpBusinessCategory, YelpBusinessNeighbors, Yelp_Review, Yelp_User
				,Yelp_User_Friend, Yelp_Checkin};
	}

	public static String[] dropTable() {
		String[] tables = {"Yelp_User_Friend", "Yelp_User", "Yelp_Checkin", 
				"YelpBusinessAttributes", "YelpBusinessCategory", "YelpBusinessNeighbors", "YelpBusiness", "Yelp_Review"};
	    String[] dropStatement = new String[tables.length];
	    
	    for (int i = 0; i < tables.length; i++) {
	    	dropStatement[i] = "drop table " + tables[i]; 
	    }
	    return dropStatement;
	}
//	public static String getStatement() {
//		// TODO Auto-generated method stub
//		return null;
//	}
}
